name: Remove old artifacts

on:
  schedule:
  # https://github.com/marketplace/actions/remove-artifacts
    - cron: '50 * * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 hour'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
